Update textx example path in README.md
secorolab/FloorPlan-DSL pull request #16
Opened 2024-07-19 12:38 UTC by LucaKro

Example should now run out of the box if you just follow the commands in the readme from top to bottom

2024-07-22 13:51 UTC, argenos reviewed
It should be possible to use the `textx generate` command from anywhere, so _technically_ the path isn't wrong.

2024-07-22 15:56 UTC, LucaKro commented
> It should be possible to use the `textx generate` command from anywhere, so _technically_ the path isn't wrong.

I mean I did not say the path was wrong, just that it doesn't work out of the box if you just follow the readme from top to bottom. Imo this is just a small quality of life adjustment, and i don't see the benefit of keeping the original over this version.

But also its not really that important, so if you want to keep the original, feel free to close this pr instead ^^

2024-07-23 08:16 UTC, argenos requested changes
Gotcha! In that case, please change the blender calls above to use `src/....` instead

2024-07-26 08:18 UTC, argenos requested changes

2024-07-26 08:18 UTC, argenos commented on README.md
> +cd src
Sorry for nitpicking. Don't cd into src, use python the same way you added in the lines above by calling Python and passing src...

Remove the ../ from the models path

2024-07-26 08:18 UTC, argenos commented on README.md
> +textx generate ../models/examples/brsu_building_c_with_doorways.floorplan --target json-ld --output-path .
Remove the ../ since we should not cd into src in the lines above

2024-07-30 03:06 UTC, LucaKro commented on README.md
> +textx generate ../models/examples/brsu_building_c_with_doorways.floorplan --target json-ld --output-path .
paths should be fixed now, if i understood your request correctly

2024-07-30 08:59 UTC, argenos approved these changes

2024-07-30 09:00 UTC, merged